language: python
python:
- '3.6'
install:
- pip install black
jobs:
  include:
  - script: black --check .
  - stage: deploy
    script: skip
    deploy:
      provider: pypi
      on:
        tags: true
      user: cxberger
      password:
        secure: p/vdIA7M0FzZG8jOSk2XBNYdIab7Cd1QeP5SIqaE8Sp52QL9FVbMA5srRqTbYUYh67lQIOxFcskCG8vyTsCAGZamuor1wOLuENyYs9gxstv5FXbdEZ0CleCp+QUkPyMmB5aL6ucuZbWHLYNsVSGXPHD8IM0mefN8r6sYL/HmPyQxl4nTtw2nv4NivgNNM2d5T/i2tvb79D80TYZDfYr9ZqqwtM1BOSl4C1CfJO8B7zg+pUmoAPKbu8UdQqD1RXuA5hVVA3tvfZIbOV7Xi/DGNRuQc+kWMw0KTyy8Ix5O84MWtfLEe/qSffv3YaXDE/8iC6rhYEkZ+nhifr4lT9iJTTNLx4RfXAQY0hIWHVFq46q5yjQO/ayk8zSksuypV/eaEhnQSxpm7y9ZL7xDO38csggm5xfauerfSqq4RtEXN5B03hlmpWAq94wlJcfvV0JcGQL5CY0c5XPNUK2jKQx+u9zNbh870DDsZ+/c7j4xcUaluDOLzLk2Qs3kiam+IgVVA6wPho3w1tUSRx/RPmctTzpPlEa5U0IDFuFsy9qW14Pj2w1msYqessKODvI+KjgFQ7uXpOaDTFAv9A55gl6MtMUm/Mfu0XuXdt67Q8yEAnhHII8mFLmgmCAefd5IlVklshWVamQhm/7EFhf8xwrTgIgajluyRJSyNQ3aVBxNy8Q=
      distributions: sdist bdist_wheel
